---
# SPDX-FileCopyrightText: 2024 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

version: '1.0.0'
name: 'White Rabbit core collection'
description: 'https://ohwr.org/project/wr-cores/wikis/home'
website: 'https://ohwr.org/project/wr-cores'
documentation: 'https://ohwr.org/project/wr-cores/wikis'
issues: 'https://ohwr.org/project/wr-cores/issues'
newsfeed: 'https://ohwr.org/project/wr-cores/wikis/news'

