--! @file        eca_auto_pkg.vhd
--  DesignUnit   eca_auto
--! @author      Wesley W. Terpstra <w.terpstra@gsi.de>
--! @date        06/04/2016
--! @version     2.0
--! @copyright   2016 GSI Helmholtz Centre for Heavy Ion Research GmbH
--!

--! @brief AUTOGENERATED WISHBONE-SLAVE PACKAGE FOR eca.vhd
--!
--------------------------------------------------------------------------------
--! This library is free software; you can redistribute it and/or
--! modify it under the terms of the GNU Lesser General Public
--! License as published by the Free Software Foundation; either
--! version 3 of the License, or (at your option) any later version.
--!
--! This library is distributed in the hope that it will be useful,
--! but WITHOUT ANY WARRANTY; without even the implied warranty of
--! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
--! Lesser General Public License for more details.
--!
--! You should have received a copy of the GNU Lesser General Public
--! License along with this library. If not, see <http://www.gnu.org/licenses/>.
--------------------------------------------------------------------------------

-- ***********************************************************
-- ** WARNING - THIS IS AUTO-GENERATED CODE! DO NOT MODIFY! **
-- ***********************************************************
--
-- If you want to change the interface,
-- modify eca.xml and re-run 'python wbgenplus.py eca.xml' !

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;
use work.wbgenplus_pkg.all;
use work.genram_pkg.all;
package eca_auto_pkg is

  constant c_channels_GET               : natural := 16#00#;  -- ro,  8 b, 
  constant c_search_capacity_GET        : natural := 16#04#;  -- ro, 16 b, 
  constant c_walker_capacity_GET        : natural := 16#08#;  -- ro, 16 b, 
  constant c_latency_GET                : natural := 16#0c#;  -- ro, 32 b, 
  constant c_offset_bits_GET            : natural := 16#10#;  -- ro,  8 b, 
  constant c_flip_active_OWR            : natural := 16#14#;  -- wo,  1 b, 
  constant c_time_hi_GET                : natural := 16#18#;  -- ro, 32 b, 
  constant c_time_lo_GET                : natural := 16#1c#;  -- ro, 32 b, 
  constant c_search_select_RW           : natural := 16#20#;  -- rw, 16 b, 
  constant c_search_ro_first_GET        : natural := 16#24#;  -- ro, 16 b, 
  constant c_search_ro_event_hi_GET     : natural := 16#28#;  -- ro, 32 b, 
  constant c_search_ro_event_lo_GET     : natural := 16#2c#;  -- ro, 32 b, 
  constant c_search_write_OWR           : natural := 16#30#;  -- wo,  1 b, 
  constant c_search_rw_first_RW         : natural := 16#34#;  -- rw, 16 b, 
  constant c_search_rw_event_hi_RW      : natural := 16#38#;  -- rw, 32 b, 
  constant c_search_rw_event_lo_RW      : natural := 16#3c#;  -- rw, 32 b, 
  constant c_walker_select_RW           : natural := 16#40#;  -- rw, 16 b, 
  constant c_walker_ro_next_GET         : natural := 16#44#;  -- ro, 16 b, 
  constant c_walker_ro_offset_hi_GET    : natural := 16#48#;  -- ro, 32 b, 
  constant c_walker_ro_offset_lo_GET    : natural := 16#4c#;  -- ro, 32 b, 
  constant c_walker_ro_tag_GET          : natural := 16#50#;  -- ro, 32 b, 
  constant c_walker_ro_flags_GET        : natural := 16#54#;  -- ro,  4 b, 
  constant c_walker_ro_channel_GET      : natural := 16#58#;  -- ro,  8 b, 
  constant c_walker_ro_num_GET          : natural := 16#5c#;  -- ro,  8 b, 
  constant c_walker_write_OWR           : natural := 16#60#;  -- wo,  1 b, 
  constant c_walker_rw_next_RW          : natural := 16#64#;  -- rw, 16 b, 
  constant c_walker_rw_offset_hi_RW     : natural := 16#68#;  -- rw, 32 b, 
  constant c_walker_rw_offset_lo_RW     : natural := 16#6c#;  -- rw, 32 b, 
  constant c_walker_rw_tag_RW           : natural := 16#70#;  -- rw, 32 b, 
  constant c_walker_rw_flags_RW         : natural := 16#74#;  -- rw,  4 b, 
  constant c_walker_rw_channel_RW       : natural := 16#78#;  -- rw,  8 b, 
  constant c_walker_rw_num_RW           : natural := 16#7c#;  -- rw,  8 b, 
  constant c_channel_select_RW          : natural := 16#80#;  -- rw,  8 b, 
  constant c_channel_num_select_RW      : natural := 16#84#;  -- rw,  8 b, 
  constant c_channel_code_select_RW     : natural := 16#88#;  -- rw,  2 b, 
  constant c_channel_type_GET           : natural := 16#8c#;  -- ro, 32 b, 
  constant c_channel_max_num_GET        : natural := 16#90#;  -- ro,  8 b, 
  constant c_channel_capacity_GET       : natural := 16#94#;  -- ro, 16 b, 
  constant c_channel_msi_set_enable_OWR : natural := 16#98#;  -- wo,  1 b, 
  constant c_channel_msi_get_enable_GET : natural := 16#9c#;  -- ro,  1 b, 
  constant c_channel_msi_set_target_OWR : natural := 16#a0#;  -- wo, 32 b, 
  constant c_channel_msi_get_target_GET : natural := 16#a4#;  -- ro, 32 b, 
  constant c_channel_overflow_count_GET : natural := 16#a8#;  -- ro, 32 b, 
  constant c_channel_mostfull_ack_GET   : natural := 16#ac#;  -- ro, 32 b, 
  constant c_channel_mostfull_clear_GET : natural := 16#b0#;  -- ro, 32 b, 
  constant c_channel_valid_count_GET    : natural := 16#b4#;  -- ro, 32 b, 
  constant c_channel_failed_count_GET   : natural := 16#b8#;  -- ro, 32 b, 
  constant c_channel_event_id_hi_GET    : natural := 16#bc#;  -- ro, 32 b, 
  constant c_channel_event_id_lo_GET    : natural := 16#c0#;  -- ro, 32 b, 
  constant c_channel_param_hi_GET       : natural := 16#c4#;  -- ro, 32 b, 
  constant c_channel_param_lo_GET       : natural := 16#c8#;  -- ro, 32 b, 
  constant c_channel_tag_GET            : natural := 16#cc#;  -- ro, 32 b, 
  constant c_channel_tef_GET            : natural := 16#d0#;  -- ro, 32 b, 
  constant c_channel_deadline_hi_GET    : natural := 16#d4#;  -- ro, 32 b, 
  constant c_channel_deadline_lo_GET    : natural := 16#d8#;  -- ro, 32 b, 
  constant c_channel_executed_hi_GET    : natural := 16#dc#;  -- ro, 32 b, 
  constant c_channel_executed_lo_GET    : natural := 16#e0#;  -- ro, 32 b, 

  --| Component ------------------------- eca_auto --------------------------------------------|
  component eca_auto is
  generic(
    g_channels        : natural := 1;   --
    g_search_capacity : natural := 512; --
    g_offset_bits     : natural := 32;  --
    g_walker_capacity : natural := 256; --
    g_latency         : natural := 4096 --
  );
  Port(
    clk_sys_i                   : std_logic;                            -- Clock input for sys domain
    rst_sys_n_i                 : std_logic;                            -- Reset input (active low) for sys domain
    channel_capacity_i          : in  std_logic_vector(16-1 downto 0);  -- 
    channel_capacity_V_i        : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_capacity
    channel_deadline_hi_i       : in  std_logic_vector(32-1 downto 0);  -- 
    channel_deadline_hi_V_i     : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_deadline_hi
    channel_deadline_lo_i       : in  std_logic_vector(32-1 downto 0);  -- 
    channel_deadline_lo_V_i     : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_deadline_lo
    channel_event_id_hi_i       : in  std_logic_vector(32-1 downto 0);  -- 
    channel_event_id_hi_V_i     : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_event_id_hi
    channel_event_id_lo_i       : in  std_logic_vector(32-1 downto 0);  -- 
    channel_event_id_lo_V_i     : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_event_id_lo
    channel_executed_hi_i       : in  std_logic_vector(32-1 downto 0);  -- 
    channel_executed_hi_V_i     : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_executed_hi
    channel_executed_lo_i       : in  std_logic_vector(32-1 downto 0);  -- 
    channel_executed_lo_V_i     : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_executed_lo
    channel_failed_count_i      : in  std_logic_vector(32-1 downto 0);  -- 
    channel_failed_count_V_i    : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_failed_count
    channel_max_num_i           : in  std_logic_vector(8-1 downto 0);   -- 
    channel_max_num_V_i         : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_max_num
    channel_mostfull_ack_i      : in  std_logic_vector(32-1 downto 0);  -- 
    channel_mostfull_ack_V_i    : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_mostfull_ack
    channel_mostfull_clear_i    : in  std_logic_vector(32-1 downto 0);  -- 
    channel_mostfull_clear_V_i  : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_mostfull_clear
    channel_msi_get_enable_i    : in  std_logic_vector(1-1 downto 0);   -- 
    channel_msi_get_enable_V_i  : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_msi_get_enable
    channel_msi_get_target_i    : in  std_logic_vector(32-1 downto 0);  -- 
    channel_msi_get_target_V_i  : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_msi_get_target
    channel_overflow_count_i    : in  std_logic_vector(32-1 downto 0);  -- 
    channel_overflow_count_V_i  : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_overflow_count
    channel_param_hi_i          : in  std_logic_vector(32-1 downto 0);  -- 
    channel_param_hi_V_i        : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_param_hi
    channel_param_lo_i          : in  std_logic_vector(32-1 downto 0);  -- 
    channel_param_lo_V_i        : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_param_lo
    channel_tag_i               : in  std_logic_vector(32-1 downto 0);  -- 
    channel_tag_V_i             : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_tag
    channel_tef_i               : in  std_logic_vector(32-1 downto 0);  -- 
    channel_tef_V_i             : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_tef
    channel_type_i              : in  std_logic_vector(32-1 downto 0);  -- 
    channel_type_V_i            : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_type
    channel_valid_count_i       : in  std_logic_vector(32-1 downto 0);  -- 
    channel_valid_count_V_i     : in  std_logic_vector(1-1 downto 0);   -- Valid flag - channel_valid_count
    error_i                     : in  std_logic_vector(1-1 downto 0);   -- Error control
    search_ro_event_hi_i        : in  std_logic_vector(32-1 downto 0);  -- 
    search_ro_event_hi_V_i      : in  std_logic_vector(1-1 downto 0);   -- Valid flag - search_ro_event_hi
    search_ro_event_lo_i        : in  std_logic_vector(32-1 downto 0);  -- 
    search_ro_event_lo_V_i      : in  std_logic_vector(1-1 downto 0);   -- Valid flag - search_ro_event_lo
    search_ro_first_i           : in  std_logic_vector(16-1 downto 0);  -- 
    search_ro_first_V_i         : in  std_logic_vector(1-1 downto 0);   -- Valid flag - search_ro_first
    stall_i                     : in  std_logic_vector(1-1 downto 0);   -- flow control
    time_hi_i                   : in  std_logic_vector(32-1 downto 0);  -- 
    time_hi_V_i                 : in  std_logic_vector(1-1 downto 0);   -- Valid flag - time_hi
    time_lo_i                   : in  std_logic_vector(32-1 downto 0);  -- 
    time_lo_V_i                 : in  std_logic_vector(1-1 downto 0);   -- Valid flag - time_lo
    walker_ro_channel_i         : in  std_logic_vector(8-1 downto 0);   -- 
    walker_ro_channel_V_i       : in  std_logic_vector(1-1 downto 0);   -- Valid flag - walker_ro_channel
    walker_ro_flags_i           : in  std_logic_vector(4-1 downto 0);   -- 
    walker_ro_flags_V_i         : in  std_logic_vector(1-1 downto 0);   -- Valid flag - walker_ro_flags
    walker_ro_next_i            : in  std_logic_vector(16-1 downto 0);  -- 
    walker_ro_next_V_i          : in  std_logic_vector(1-1 downto 0);   -- Valid flag - walker_ro_next
    walker_ro_num_i             : in  std_logic_vector(8-1 downto 0);   -- 
    walker_ro_num_V_i           : in  std_logic_vector(1-1 downto 0);   -- Valid flag - walker_ro_num
    walker_ro_offset_hi_i       : in  std_logic_vector(32-1 downto 0);  -- 
    walker_ro_offset_hi_V_i     : in  std_logic_vector(1-1 downto 0);   -- Valid flag - walker_ro_offset_hi
    walker_ro_offset_lo_i       : in  std_logic_vector(32-1 downto 0);  -- 
    walker_ro_offset_lo_V_i     : in  std_logic_vector(1-1 downto 0);   -- Valid flag - walker_ro_offset_lo
    walker_ro_tag_i             : in  std_logic_vector(32-1 downto 0);  -- 
    walker_ro_tag_V_i           : in  std_logic_vector(1-1 downto 0);   -- Valid flag - walker_ro_tag
    channel_code_select_o       : out std_logic_vector(2-1 downto 0);   -- 
    channel_deadline_hi_RD_o    : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_deadline_hi
    channel_deadline_lo_RD_o    : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_deadline_lo
    channel_event_id_hi_RD_o    : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_event_id_hi
    channel_event_id_lo_RD_o    : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_event_id_lo
    channel_executed_hi_RD_o    : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_executed_hi
    channel_executed_lo_RD_o    : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_executed_lo
    channel_failed_count_RD_o   : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_failed_count
    channel_mostfull_ack_RD_o   : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_mostfull_ack
    channel_mostfull_clear_RD_o : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_mostfull_clear
    channel_msi_set_enable_o    : out std_logic_vector(1-1 downto 0);   -- 
    channel_msi_set_enable_WR_o : out std_logic_vector(1-1 downto 0);   -- Write enable flag - channel_msi_set_enable
    channel_msi_set_target_o    : out std_logic_vector(32-1 downto 0);  -- 
    channel_msi_set_target_WR_o : out std_logic_vector(1-1 downto 0);   -- Write enable flag - channel_msi_set_target
    channel_num_select_o        : out std_logic_vector(8-1 downto 0);   -- 
    channel_overflow_count_RD_o : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_overflow_count
    channel_param_hi_RD_o       : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_param_hi
    channel_param_lo_RD_o       : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_param_lo
    channel_select_o            : out std_logic_vector(8-1 downto 0);   -- 
    channel_select_RD_o         : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_select
    channel_select_WR_o         : out std_logic_vector(1-1 downto 0);   -- Write enable flag - channel_select
    channel_tag_RD_o            : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_tag
    channel_tef_RD_o            : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_tef
    channel_valid_count_RD_o    : out std_logic_vector(1-1 downto 0);   -- Read enable flag - channel_valid_count
    flip_active_o               : out std_logic_vector(1-1 downto 0);   -- 
    search_rw_event_hi_o        : out std_logic_vector(32-1 downto 0);  -- 
    search_rw_event_lo_o        : out std_logic_vector(32-1 downto 0);  -- 
    search_rw_first_o           : out std_logic_vector(16-1 downto 0);  -- 
    search_select_o             : out std_logic_vector(16-1 downto 0);  -- 
    search_select_RD_o          : out std_logic_vector(1-1 downto 0);   -- Read enable flag - search_select
    search_select_WR_o          : out std_logic_vector(1-1 downto 0);   -- Write enable flag - search_select
    search_write_o              : out std_logic_vector(1-1 downto 0);   -- 
    walker_rw_channel_o         : out std_logic_vector(8-1 downto 0);   -- 
    walker_rw_flags_o           : out std_logic_vector(4-1 downto 0);   -- 
    walker_rw_next_o            : out std_logic_vector(16-1 downto 0);  -- 
    walker_rw_num_o             : out std_logic_vector(8-1 downto 0);   -- 
    walker_rw_offset_hi_o       : out std_logic_vector(32-1 downto 0);  -- 
    walker_rw_offset_lo_o       : out std_logic_vector(32-1 downto 0);  -- 
    walker_rw_tag_o             : out std_logic_vector(32-1 downto 0);  -- 
    walker_select_o             : out std_logic_vector(16-1 downto 0);  -- 
    walker_select_RD_o          : out std_logic_vector(1-1 downto 0);   -- Read enable flag - walker_select
    walker_select_WR_o          : out std_logic_vector(1-1 downto 0);   -- Write enable flag - walker_select
    walker_write_o              : out std_logic_vector(1-1 downto 0);   -- 
    
    slave_i                     : in  t_wishbone_slave_in;
    slave_o                     : out t_wishbone_slave_out

    
  );
  end component;

  constant c_eca_slave_sdb : t_sdb_device := (
  abi_class     => x"0000", -- undocumented device
  abi_ver_major => x"01",
  abi_ver_minor => x"00",
  wbd_endian    => c_sdb_endian_big,
  wbd_width     => x"7", -- 8/16/32-bit port granularity
  sdb_component => (
  addr_first    => x"0000000000000000",
  addr_last     => x"00000000000000ff",
  product => (
  vendor_id     => x"0000000000000651",
  device_id     => x"b2afc251",
  version       => x"00000020",
  date          => x"20160406",
  name          => "ECA_UNIT:CONTROL   ")));

end eca_auto_pkg;
package body eca_auto_pkg is
end eca_auto_pkg;
