-- Do not edit.  Generated by cheby 1.6.dev0 using these options:
--  -i irig_slave_regs.cheby --gen-hdl irig_slave_regs.vhd
-- Generated on Thu Oct 24 14:19:28 2024 by harvey


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package irig_slave_regs_pkg is
  type t_irig_regs_master_out is record
    CR_enable        : std_logic;
  end record t_irig_regs_master_out;
  subtype t_irig_regs_slave_in is t_irig_regs_master_out;

  type t_irig_regs_slave_out is record
    TOD_seconds      : std_logic_vector(7 downto 0);
    TOD_minutes      : std_logic_vector(8 downto 0);
    TOD_hours        : std_logic_vector(8 downto 0);
    TOD_valid        : std_logic;
    DATE_days        : std_logic_vector(10 downto 0);
    DATE_years       : std_logic_vector(8 downto 0);
    DATE_valid       : std_logic;
    CTRL_fcn0        : std_logic_vector(8 downto 0);
    CTRL_fcn1        : std_logic_vector(8 downto 0);
    CTRL_valid       : std_logic;
    SBS_sbs          : std_logic_vector(17 downto 0);
    SBS_valid        : std_logic;
  end record t_irig_regs_slave_out;
  subtype t_irig_regs_master_in is t_irig_regs_slave_out;

end irig_slave_regs_pkg;

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.irig_slave_regs_pkg.all;

entity irig_slave_regs is
  port (
    rst_n_i              : in    std_logic;
    clk_i                : in    std_logic;
    wb_cyc_i             : in    std_logic;
    wb_stb_i             : in    std_logic;
    wb_adr_i             : in    std_logic_vector(4 downto 2);
    wb_sel_i             : in    std_logic_vector(3 downto 0);
    wb_we_i              : in    std_logic;
    wb_dat_i             : in    std_logic_vector(31 downto 0);
    wb_ack_o             : out   std_logic;
    wb_err_o             : out   std_logic;
    wb_rty_o             : out   std_logic;
    wb_stall_o           : out   std_logic;
    wb_dat_o             : out   std_logic_vector(31 downto 0);
    -- Wires and registers
    irig_regs_i          : in    t_irig_regs_master_in;
    irig_regs_o          : out   t_irig_regs_master_out
  );
end irig_slave_regs;

architecture syn of irig_slave_regs is
  signal rd_req_int                     : std_logic;
  signal wr_req_int                     : std_logic;
  signal rd_ack_int                     : std_logic;
  signal wr_ack_int                     : std_logic;
  signal wb_en                          : std_logic;
  signal ack_int                        : std_logic;
  signal wb_rip                         : std_logic;
  signal wb_wip                         : std_logic;
  signal CR_enable_reg                  : std_logic;
  signal CR_wreq                        : std_logic;
  signal CR_wack                        : std_logic;
  signal rd_ack_d0                      : std_logic;
  signal rd_dat_d0                      : std_logic_vector(31 downto 0);
  signal wr_req_d0                      : std_logic;
  signal wr_adr_d0                      : std_logic_vector(4 downto 2);
  signal wr_dat_d0                      : std_logic_vector(31 downto 0);
begin

  -- WB decode signals
  wb_en <= wb_cyc_i and wb_stb_i;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_rip <= '0';
      else
        wb_rip <= (wb_rip or (wb_en and not wb_we_i)) and not rd_ack_int;
      end if;
    end if;
  end process;
  rd_req_int <= (wb_en and not wb_we_i) and not wb_rip;

  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        wb_wip <= '0';
      else
        wb_wip <= (wb_wip or (wb_en and wb_we_i)) and not wr_ack_int;
      end if;
    end if;
  end process;
  wr_req_int <= (wb_en and wb_we_i) and not wb_wip;

  ack_int <= rd_ack_int or wr_ack_int;
  wb_ack_o <= ack_int;
  wb_stall_o <= not ack_int and wb_en;
  wb_rty_o <= '0';
  wb_err_o <= '0';

  -- pipelining for wr-in+rd-out
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        rd_ack_int <= '0';
        wb_dat_o <= "00000000000000000000000000000000";
        wr_req_d0 <= '0';
        wr_adr_d0 <= "000";
        wr_dat_d0 <= "00000000000000000000000000000000";
      else
        rd_ack_int <= rd_ack_d0;
        wb_dat_o <= rd_dat_d0;
        wr_req_d0 <= wr_req_int;
        wr_adr_d0 <= wb_adr_i;
        wr_dat_d0 <= wb_dat_i;
      end if;
    end if;
  end process;

  -- Register CR
  irig_regs_o.CR_enable <= CR_enable_reg;
  process (clk_i) begin
    if rising_edge(clk_i) then
      if rst_n_i = '0' then
        CR_enable_reg <= '0';
        CR_wack <= '0';
      else
        if CR_wreq = '1' then
          CR_enable_reg <= wr_dat_d0(0);
        end if;
        CR_wack <= CR_wreq;
      end if;
    end if;
  end process;

  -- Register TOD

  -- Register DATE

  -- Register CTRL

  -- Register SBS

  -- Process for write requests.
  process (wr_adr_d0, wr_req_d0, CR_wack) begin
    CR_wreq <= '0';
    case wr_adr_d0(4 downto 2) is
    when "000" =>
      -- Reg CR
      CR_wreq <= wr_req_d0;
      wr_ack_int <= CR_wack;
    when "001" =>
      -- Reg TOD
      wr_ack_int <= wr_req_d0;
    when "010" =>
      -- Reg DATE
      wr_ack_int <= wr_req_d0;
    when "011" =>
      -- Reg CTRL
      wr_ack_int <= wr_req_d0;
    when "100" =>
      -- Reg SBS
      wr_ack_int <= wr_req_d0;
    when others =>
      wr_ack_int <= wr_req_d0;
    end case;
  end process;

  -- Process for read requests.
  process (wb_adr_i, rd_req_int, CR_enable_reg, irig_regs_i.TOD_seconds,
           irig_regs_i.TOD_minutes, irig_regs_i.TOD_hours,
           irig_regs_i.TOD_valid, irig_regs_i.DATE_days,
           irig_regs_i.DATE_years, irig_regs_i.DATE_valid,
           irig_regs_i.CTRL_fcn0, irig_regs_i.CTRL_fcn1,
           irig_regs_i.CTRL_valid, irig_regs_i.SBS_sbs, irig_regs_i.SBS_valid) begin
    -- By default ack read requests
    rd_dat_d0 <= (others => 'X');
    case wb_adr_i(4 downto 2) is
    when "000" =>
      -- Reg CR
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(0) <= CR_enable_reg;
      rd_dat_d0(31 downto 1) <= (others => '0');
    when "001" =>
      -- Reg TOD
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(7 downto 0) <= irig_regs_i.TOD_seconds;
      rd_dat_d0(16 downto 8) <= irig_regs_i.TOD_minutes;
      rd_dat_d0(19 downto 17) <= (others => '0');
      rd_dat_d0(28 downto 20) <= irig_regs_i.TOD_hours;
      rd_dat_d0(30 downto 29) <= (others => '0');
      rd_dat_d0(31) <= irig_regs_i.TOD_valid;
    when "010" =>
      -- Reg DATE
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(10 downto 0) <= irig_regs_i.DATE_days;
      rd_dat_d0(15 downto 11) <= (others => '0');
      rd_dat_d0(24 downto 16) <= irig_regs_i.DATE_years;
      rd_dat_d0(30 downto 25) <= (others => '0');
      rd_dat_d0(31) <= irig_regs_i.DATE_valid;
    when "011" =>
      -- Reg CTRL
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(8 downto 0) <= irig_regs_i.CTRL_fcn0;
      rd_dat_d0(15 downto 9) <= (others => '0');
      rd_dat_d0(24 downto 16) <= irig_regs_i.CTRL_fcn1;
      rd_dat_d0(30 downto 25) <= (others => '0');
      rd_dat_d0(31) <= irig_regs_i.CTRL_valid;
    when "100" =>
      -- Reg SBS
      rd_ack_d0 <= rd_req_int;
      rd_dat_d0(17 downto 0) <= irig_regs_i.SBS_sbs;
      rd_dat_d0(30 downto 18) <= (others => '0');
      rd_dat_d0(31) <= irig_regs_i.SBS_valid;
    when others =>
      rd_ack_d0 <= rd_req_int;
    end case;
  end process;
end syn;
